name: Nx build
on: [push, pull_request]
env:
  BEFORE_SHA: ${{ github.event.before }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Configure CI Git User
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: config private registry
        run: npm config set '@paladin-analytics:registry' "https://npm.pkg.github.com"
      - run: npm config set '//npm.pkg.github.com/:_authToken' "${GITHUB_TOKEN}"
      - name: yarn install
        run: yarn install
      - name: building app and lib
        run: npm run build
